### PR TITLE
Add tags support

### PR DESCRIPTION
**Pull request by rfunduk**
Hello there! Working on a ConvertKit integration and needed tags support as well as non-global API key configuration.

This PR has that and a few other small things:

- add `.env.local.sample` file which can be copied to get a working `.env.local` which is needed for testing purposes
- pull out some of the hard coded values in the tests into those env variables
- accept `api_key` and `api_secret` in client initialization
- default `api_key` and `api_secret` to `nil` so that when making a request the string `'api_key'` and `'api_secret'` aren't sent to convertkit (this is a problem when you dont need/want to specify `api_secret`, and that string is sent along anyway)
- there was some mixing of tabs and spaces, i think i caught them all and made them spaces
- bump to 0.0.2
- removed the need to make 2 requests per test (use same response to check success and body)

I hope this looks good!

### CODE REVIEW

**Comment by rfunduk** [comment]
I thought the tests might fail since a `.env.local` is required now. I wonder how it's making API calls at all though since `API_KEY` and `API_SECRET` env variables were needed all along.

**Comment by rkcudjoe** [comment]
@rfunduk I had a convertkit account, and I used the `api_key` and `api_secret` on Semaphore to run the tests. I'l merge this PR if you can confirm all tests are passing on your local machine w/ a screenshot.

**Comment by rkcudjoe** [comment]
@rfunduk 💯  got the tests to pass!

**Comment by rfunduk** [comment]
🍠  Awesome!

**Pull request merged**
